
- name: Create Packer directory
  ansible.builtin.file:
    path: "{{ packer_dir  }}"
    state: directory

- name: Download ISO
  ansible.builtin.get_url:
    url: "{{ packer_iso_url }}"
    dest: "{{ packer_dir  }}/{{ packer_iso_url | basename }}"
    mode: '0440'
    checksum: "{{ packer_iso_checksum }}"

- name: Create directory for storing the kernel and ramdisk
  ansible.builtin.file:
    path: "{{ packer_dir  }}/{{ packer_iso_url | basename }}-extract"
    state: directory

- name: Extract the kernel and ramdisk from the ISO
  community.general.iso_extract:
    image: "{{ packer_dir  }}/{{ packer_iso_url | basename }}"
    dest: "{{ packer_dir  }}/{{ packer_iso_url | basename }}-extract"
    files:
    - images/pxeboot/vmlinuz
    - images/pxeboot/initrd.img

# - name: Create a floppy disk containing the kickstart file
#   ansible.builtin.shell: >
#     dd if=/dev/zero of={{ packer_ks_floppy | quote }} bs=1440K count=1
#     && mkfs.ext4 {{ packer_ks_floppy | quote }}
#     && mkdir {{ packer_dir | quote }}/mnt
#     && sudo mount {{ packer_ks_floppy | quote }} {{ packer_dir | quote }}/mnt
#     && cp -p {{ packer_kickstart_file | quote }} {{ packer_dir | quote }}/mnt
#     && sudo umount {{ packer_dir | quote }}/mnt
#     && rmdir {{ packer_dir | quote }}/mnt