
all:
  hosts:
    workbench.execnop.com:
      ansible_host: 192.168.140.4
  children:
    kvm:
      hosts:
        kvm1.execnop.com:
          ansible_host: 192.168.140.1
    infra_containers:
      hosts:
        ns1.execnop.com:
          ansible_host: 192.168.141.4
        ipa1.execnop.com:
          ansible_host: 192.168.141.5
