---
- name: Bastion setup
  hosts: localhost
  tasks:

    - name: Generate SSH keys for root
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_ed25519
        type: ed25519

    - name: Add Hashicorp repo
      ansible.builtin.yum_repository:
        name: terraform
        description: Official Hashicorp repo
        baseurl:
          - https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

    - name: Install packages
      ansible.builtin.yum:
        name:
          - terraform
          - packer
          - git
          #- qemu-system-x86
          - tmux
          - python3
          - python3-pip
        state: latest

    - name: Install pipenv
      ansible.builtin.command: python3 -m pip install --user pipenv

    - name: Create pipenv from requirements.txt
      ansible.builtin.command: pipenv install -r LOCATION?



    # run terraform init
