- name: Configure KVM host
  hosts: kvm_hosts
  tasks:

    - name: Add Hashicorp repo
      ansible.builtin.yum_repository:
        name: terraform
        description: Official Hashicorp repo
        baseurl:
          - https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

    - name: Install packages
      ansible.builtin.yum:
        name: []
        state: latest
